import { Ionicons } from "@expo/vector-icons";
import * as FileSystem from "expo-file-system";
import * as MediaLibrary from "expo-media-library";
import { Image } from "expo-image";
import { useLocalSearchParams, useRouter } from "expo-router";
import { useState } from "react";
import { ActivityIndicator, Alert, Linking, Platform, Pressable, Text, View } from "react-native";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import { makeStyles, useTheme } from "@/src/theme";

export default function Details() {
  const styles = useStyles(); const { colors } = useTheme(); const insets = useSafeAreaInsets(); const router = useRouter(); const params = useLocalSearchParams<{ id: string; author: string; width: string; height: string; url: string; download_url: string; thumbnail_url: string }>(); const [saved, setSaved] = useState(false); const [downloading, setDownloading] = useState(false); const [error, setError] = useState("");
  const download = async () => { setDownloading(true); setError(""); try { if (Platform.OS === "web") { await Linking.openURL(params.download_url || params.url); return; } const permission = await MediaLibrary.requestPermissionsAsync(); if (!permission.granted) throw new Error("Photo permission is needed to save this image."); const file = await FileSystem.downloadAsync(params.download_url || params.url, `${FileSystem.cacheDirectory}aura-${params.id}.jpg`); const asset = await MediaLibrary.createAssetAsync(file.uri); try { await MediaLibrary.createAlbumAsync("Aura Picsum", asset, false); } catch { /* album can already exist */ } Alert.alert("Saved to gallery", "Your image is ready in the Aura Picsum album."); } catch (downloadError) { setError((downloadError as Error).message || "Download failed. Please try again."); } finally { setDownloading(false); } };
  return <View style={styles.root}><View style={[styles.top, { paddingTop: insets.top + 10 }]}><Pressable onPress={() => router.back()} style={styles.iconButton} accessibilityLabel="Go back"><Ionicons name="arrow-back" size={23} color={colors.onSurfaceInverse} /></Pressable><Text style={styles.topLabel}>IMAGE DETAIL</Text><Pressable onPress={() => setSaved((value) => !value)} style={styles.iconButton} accessibilityLabel={saved ? "Remove favorite" : "Add favorite"><Ionicons name={saved ? "heart" : "heart-outline"} size={22} color={saved ? colors.brandTertiary : colors.onSurfaceInverse} /></Pressable></View><Image source={{ uri: params.url || params.thumbnail_url }} placeholder={{ uri: params.thumbnail_url }} style={styles.hero} contentFit="contain" transition={220} /><View style={[styles.sheet, { paddingBottom: insets.bottom + 20 }]}><Text style={styles.eyebrow}>CAPTURED BY</Text><Text style={styles.author}>{params.author || "Unknown author"}</Text><View style={styles.rule} /><View style={styles.metadata}><View><Text style={styles.metaLabel}>DIMENSIONS</Text><Text style={styles.metaValue}>{params.width} × {params.height}</Text></View><View><Text style={styles.metaLabel}>SOURCE</Text><Text style={styles.metaValue}>PICSUM</Text></View></View>{error ? <Text style={styles.error}>{error}</Text> : null}<Pressable onPress={download} disabled={downloading} style={({ pressed }) => [styles.download, pressed && styles.pressed, downloading && styles.disabled]}>{downloading ? <ActivityIndicator color={colors.onBrandPrimary} /> : <><Ionicons name="download-outline" size={19} color={colors.onBrandPrimary} /><Text style={styles.downloadText}>Save image</Text></>}</Pressable></View></View>;
}
const useStyles = makeStyles((colors) => ({ root: { flex: 1, backgroundColor: colors.surfaceInverse }, top: { minHeight: 62, flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingHorizontal: 18 }, topLabel: { color: colors.onSurfaceInverse, fontSize: 11, fontWeight: "800", letterSpacing: 1.5 }, iconButton: { minWidth: 44, minHeight: 44, justifyContent: "center", alignItems: "center" }, hero: { flex: 1, width: "100%" }, sheet: { backgroundColor: colors.surface, borderTopLeftRadius: 24, borderTopRightRadius: 24, paddingHorizontal: 22, paddingTop: 24 }, eyebrow: { color: colors.brand, fontSize: 11, fontWeight: "800", letterSpacing: 1.4 }, author: { color: colors.onSurface, fontFamily: "Georgia", fontSize: 30, marginTop: 7 }, rule: { height: 1, backgroundColor: colors.divider, marginVertical: 20 }, metadata: { flexDirection: "row", gap: 44 }, metaLabel: { color: colors.muted, fontSize: 10, fontWeight: "800", letterSpacing: 1 }, metaValue: { color: colors.onSurfaceSecondary, fontSize: 15, fontWeight: "700", marginTop: 5 }, download: { minHeight: 52, flexDirection: "row", justifyContent: "center", alignItems: "center", gap: 9, backgroundColor: colors.brandPrimary, borderRadius: 12, marginTop: 24 }, downloadText: { color: colors.onBrandPrimary, fontSize: 16, fontWeight: "800" }, error: { color: colors.error, fontSize: 13, marginTop: 18 }, pressed: { opacity: 0.8 }, disabled: { opacity: 0.6 } }));
