import { Ionicons } from "@expo/vector-icons";
import { useLocalSearchParams, useRouter } from "expo-router";
import { useState } from "react";
import { ActivityIndicator, KeyboardAvoidingView, Platform, Pressable, Text, TextInput, View } from "react-native";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import { api } from "@/src/api";
import { makeStyles, useTheme } from "@/src/theme";

export default function Reset() { const styles = useStyles(); const { colors } = useTheme(); const insets = useSafeAreaInsets(); const router = useRouter(); const params = useLocalSearchParams<{ token?: string }>(); const [password, setPassword] = useState(""); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState(""); const submit = async () => { setBusy(true); setError(""); try { const response = await api.resetPassword(String(params.token || ""), password); setMessage(response.message); } catch (resetError) { setError((resetError as Error).message); } finally { setBusy(false); } }; return <KeyboardAvoidingView behavior={Platform.OS === "ios" ? "padding" : "height"} style={[styles.root, { paddingTop: insets.top + 24, paddingBottom: insets.bottom + 20 }]}><Pressable onPress={() => router.replace("/")} style={styles.back}><Ionicons name="arrow-back" size={22} color={colors.onSurface} /><Text style={styles.backText}>Back to sign in</Text></Pressable><View style={styles.content}><Ionicons name="key-outline" size={30} color={colors.brand} /><Text style={styles.title}>Choose a new password.</Text><Text style={styles.subtitle}>This recovery link is single-use and expires after 30 minutes.</Text><Text style={styles.label}>NEW PASSWORD</Text><TextInput value={password} onChangeText={setPassword} secureTextEntry placeholder="8 characters minimum" placeholderTextColor={colors.muted} style={styles.input} /><Text style={styles.feedback}>{error || message}</Text><Pressable onPress={submit} disabled={busy || !params.token} style={[styles.primary, busy && styles.disabled]}>{busy ? <ActivityIndicator color={colors.onBrandPrimary} /> : <Text style={styles.primaryText}>Update password</Text>}</Pressable></View></KeyboardAvoidingView>; }
const useStyles = makeStyles((colors) => ({ root: { flex: 1, backgroundColor: colors.surface, paddingHorizontal: 26 }, back: { minHeight: 44, flexDirection: "row", alignItems: "center", gap: 8 }, backText: { color: colors.onSurface, fontWeight: "700" }, content: { flex: 1, justifyContent: "center", gap: 16 }, title: { color: colors.onSurface, fontFamily: "Georgia", fontSize: 32, lineHeight: 39 }, subtitle: { color: colors.muted, fontSize: 15, lineHeight: 22, marginBottom: 14 }, label: { color: colors.onSurfaceSecondary, fontSize: 11, fontWeight: "800", letterSpacing: 1.2 }, input: { color: colors.onSurface, fontSize: 16, minHeight: 50, borderBottomWidth: 1, borderBottomColor: colors.borderStrong }, feedback: { color: colors.error, minHeight: 20, fontSize: 13 }, primary: { minHeight: 52, borderRadius: 12, backgroundColor: colors.brandPrimary, alignItems: "center", justifyContent: "center" }, primaryText: { color: colors.onBrandPrimary, fontSize: 16, fontWeight: "800" }, disabled: { opacity: 0.6 } }));
